// ─── Synthetic Participant Pool ──────────────────────────────
// 42 curated ambient coworkers across 4 archetypes.
// They generate lightweight activity events so rooms feel alive
// even when real-user density is low.

export type SyntheticArchetype = "coder" | "writer" | "founder" | "gentle";

/** Event types a synthetic participant can generate. */
export type SyntheticEventType =
  | "participant_joined"
  | "session_started"
  | "sprint_completed"
  | "session_completed"
  | "participant_left"
  | "check_in"
  | "high_five";

export interface SyntheticParticipant {
  /** Stable identifier — stored in payload.synthetic_id, never in user_id FK. */
  id: string;
  handle: string;
  displayName: string;
  /** AI-generated avatar URL (Supabase storage). */
  avatarUrl: string;
  archetype: SyntheticArchetype;
  /** Worlds this synthetic prefers (higher affinity for appearing). */
  preferredWorldKeys: string[];
  /** Relative weights for each event type. Higher = more likely. */
  activityBias: Record<SyntheticEventType, number>;
}

// ─── Pool ────────────────────────────────────────────────────

export const SYNTHETIC_POOL: SyntheticParticipant[] = [
  // ── Coders ──
  {
    id: "syn-kai",
    handle: "kai",
    displayName: "Kai",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/kai/thumb.png",
    archetype: "coder",
    preferredWorldKeys: ["vibe-coding", "default", "yc-build"],
    activityBias: {
      participant_joined: 1.0,
      session_started: 1.2,
      sprint_completed: 1.5,
      session_completed: 1.0,
      participant_left: 0.8,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-rio",
    handle: "rio",
    displayName: "Rio",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/rio/thumb.png",
    archetype: "coder",
    preferredWorldKeys: ["vibe-coding", "default"],
    activityBias: {
      participant_joined: 1.0,
      session_started: 1.3,
      sprint_completed: 1.4,
      session_completed: 0.9,
      participant_left: 0.7,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-dev",
    handle: "dev",
    displayName: "Dev",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/dev/thumb.png",
    archetype: "coder",
    preferredWorldKeys: ["vibe-coding", "yc-build", "default"],
    activityBias: {
      participant_joined: 0.9,
      session_started: 1.1,
      sprint_completed: 1.6,
      session_completed: 1.1,
      participant_left: 0.8,
      check_in: 0.8,
      high_five: 0.3,
    },
  },

  // ── Writers ──
  {
    id: "syn-sage",
    handle: "sage",
    displayName: "Sage",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/sage/thumb.png",
    archetype: "writer",
    preferredWorldKeys: ["writer-room", "default", "gentle-start"],
    activityBias: {
      participant_joined: 1.0,
      session_started: 1.1,
      sprint_completed: 1.3,
      session_completed: 1.0,
      participant_left: 0.9,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-ellis",
    handle: "ellis",
    displayName: "Ellis",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/ellis/thumb.png",
    archetype: "writer",
    preferredWorldKeys: ["writer-room", "default"],
    activityBias: {
      participant_joined: 1.0,
      session_started: 1.2,
      sprint_completed: 1.2,
      session_completed: 1.0,
      participant_left: 0.8,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-wren",
    handle: "wren",
    displayName: "Wren",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/wren/thumb.png",
    archetype: "writer",
    preferredWorldKeys: ["writer-room", "gentle-start", "default"],
    activityBias: {
      participant_joined: 1.1,
      session_started: 1.0,
      sprint_completed: 1.4,
      session_completed: 1.1,
      participant_left: 0.7,
      check_in: 0.8,
      high_five: 0.3,
    },
  },

  // ── Founders ──
  {
    id: "syn-ava",
    handle: "ava",
    displayName: "Ava",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/ava/thumb.png",
    archetype: "founder",
    preferredWorldKeys: ["yc-build", "default", "vibe-coding"],
    activityBias: {
      participant_joined: 1.0,
      session_started: 1.4,
      sprint_completed: 1.5,
      session_completed: 0.9,
      participant_left: 0.6,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-noor",
    handle: "noor",
    displayName: "Noor",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/noor/thumb.png",
    archetype: "founder",
    preferredWorldKeys: ["yc-build", "default"],
    activityBias: {
      participant_joined: 1.0,
      session_started: 1.3,
      sprint_completed: 1.3,
      session_completed: 1.0,
      participant_left: 0.8,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-quinn",
    handle: "quinn",
    displayName: "Quinn",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/quinn/thumb.png",
    archetype: "founder",
    preferredWorldKeys: ["yc-build", "vibe-coding", "default"],
    activityBias: {
      participant_joined: 0.9,
      session_started: 1.2,
      sprint_completed: 1.6,
      session_completed: 1.0,
      participant_left: 0.7,
      check_in: 0.8,
      high_five: 0.3,
    },
  },

  // ── Gentle ──
  {
    id: "syn-lux",
    handle: "lux",
    displayName: "Lux",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/lux/thumb.png",
    archetype: "gentle",
    preferredWorldKeys: ["gentle-start", "default", "writer-room"],
    activityBias: {
      participant_joined: 1.1,
      session_started: 1.0,
      sprint_completed: 1.2,
      session_completed: 1.1,
      participant_left: 0.9,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-sol",
    handle: "sol",
    displayName: "Sol",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/sol/thumb.png",
    archetype: "gentle",
    preferredWorldKeys: ["gentle-start", "default"],
    activityBias: {
      participant_joined: 1.0,
      session_started: 1.1,
      sprint_completed: 1.1,
      session_completed: 1.0,
      participant_left: 1.0,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-fern",
    handle: "fern",
    displayName: "Fern",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/fern/thumb.png",
    archetype: "gentle",
    preferredWorldKeys: ["gentle-start", "writer-room", "default"],
    activityBias: {
      participant_joined: 1.0,
      session_started: 1.0,
      sprint_completed: 1.3,
      session_completed: 1.0,
      participant_left: 0.8,
      check_in: 0.8,
      high_five: 0.3,
    },
  },

  // ═══════════════════════════════════════════════════════════
  //  Wave 2 — 30 additional ambient coworkers
  // ═══════════════════════════════════════════════════════════

  // ── Coders (8) ──

  {
    id: "syn-jax",
    handle: "jax",
    displayName: "Jax",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/jax/thumb.png",
    archetype: "coder",
    preferredWorldKeys: ["vibe-coding", "default"],
    activityBias: {
      participant_joined: 0.9,
      session_started: 1.4,
      sprint_completed: 1.5,
      session_completed: 0.8,
      participant_left: 0.6,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-rune",
    handle: "rune",
    displayName: "Rune",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/rune/thumb.png",
    archetype: "coder",
    preferredWorldKeys: ["vibe-coding", "yc-build"],
    activityBias: {
      participant_joined: 1.0,
      session_started: 1.1,
      sprint_completed: 1.7,
      session_completed: 1.0,
      participant_left: 0.7,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-kit",
    handle: "kit",
    displayName: "Kit",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/kit/thumb.png",
    archetype: "coder",
    preferredWorldKeys: ["vibe-coding", "default", "yc-build"],
    activityBias: {
      participant_joined: 1.1,
      session_started: 1.2,
      sprint_completed: 1.3,
      session_completed: 1.1,
      participant_left: 0.9,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-nova",
    handle: "nova",
    displayName: "Nova",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/nova/thumb.png",
    archetype: "coder",
    preferredWorldKeys: ["vibe-coding", "default"],
    activityBias: {
      participant_joined: 1.0,
      session_started: 1.3,
      sprint_completed: 1.4,
      session_completed: 0.9,
      participant_left: 0.8,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-hex",
    handle: "hex",
    displayName: "Hex",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/hex/thumb.png",
    archetype: "coder",
    preferredWorldKeys: ["vibe-coding", "yc-build", "default"],
    activityBias: {
      participant_joined: 0.8,
      session_started: 1.0,
      sprint_completed: 1.8,
      session_completed: 1.0,
      participant_left: 0.6,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-taz",
    handle: "taz",
    displayName: "Taz",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/taz/thumb.png",
    archetype: "coder",
    preferredWorldKeys: ["vibe-coding", "default"],
    activityBias: {
      participant_joined: 1.0,
      session_started: 1.5,
      sprint_completed: 1.3,
      session_completed: 0.8,
      participant_left: 0.9,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-byte",
    handle: "byte",
    displayName: "Byte",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/byte/thumb.png",
    archetype: "coder",
    preferredWorldKeys: ["vibe-coding", "yc-build"],
    activityBias: {
      participant_joined: 0.9,
      session_started: 1.2,
      sprint_completed: 1.6,
      session_completed: 1.1,
      participant_left: 0.7,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-pixel",
    handle: "pixel",
    displayName: "Pixel",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/pixel/thumb.png",
    archetype: "coder",
    preferredWorldKeys: ["vibe-coding", "default", "yc-build"],
    activityBias: {
      participant_joined: 1.1,
      session_started: 1.1,
      sprint_completed: 1.4,
      session_completed: 1.0,
      participant_left: 0.8,
      check_in: 0.8,
      high_five: 0.3,
    },
  },

  // ── Writers (8) ──

  {
    id: "syn-muse",
    handle: "muse",
    displayName: "Muse",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/muse/thumb.png",
    archetype: "writer",
    preferredWorldKeys: ["writer-room", "default"],
    activityBias: {
      participant_joined: 1.0,
      session_started: 1.3,
      sprint_completed: 1.2,
      session_completed: 1.1,
      participant_left: 0.8,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-reed",
    handle: "reed",
    displayName: "Reed",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/reed/thumb.png",
    archetype: "writer",
    preferredWorldKeys: ["writer-room", "gentle-start", "default"],
    activityBias: {
      participant_joined: 1.1,
      session_started: 1.0,
      sprint_completed: 1.3,
      session_completed: 1.0,
      participant_left: 0.9,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-lyra",
    handle: "lyra",
    displayName: "Lyra",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/lyra/thumb.png",
    archetype: "writer",
    preferredWorldKeys: ["writer-room", "default"],
    activityBias: {
      participant_joined: 1.0,
      session_started: 1.2,
      sprint_completed: 1.1,
      session_completed: 1.0,
      participant_left: 0.7,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-poe",
    handle: "poe",
    displayName: "Poe",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/poe/thumb.png",
    archetype: "writer",
    preferredWorldKeys: ["writer-room", "default", "gentle-start"],
    activityBias: {
      participant_joined: 0.9,
      session_started: 1.1,
      sprint_completed: 1.4,
      session_completed: 1.1,
      participant_left: 0.8,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-clio",
    handle: "clio",
    displayName: "Clio",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/clio/thumb.png",
    archetype: "writer",
    preferredWorldKeys: ["writer-room", "gentle-start"],
    activityBias: {
      participant_joined: 1.0,
      session_started: 1.0,
      sprint_completed: 1.3,
      session_completed: 1.2,
      participant_left: 0.9,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-bly",
    handle: "bly",
    displayName: "Bly",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/bly/thumb.png",
    archetype: "writer",
    preferredWorldKeys: ["writer-room", "default"],
    activityBias: {
      participant_joined: 1.1,
      session_started: 1.2,
      sprint_completed: 1.1,
      session_completed: 0.9,
      participant_left: 0.7,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-ink",
    handle: "ink",
    displayName: "Ink",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/ink/thumb.png",
    archetype: "writer",
    preferredWorldKeys: ["writer-room", "default", "gentle-start"],
    activityBias: {
      participant_joined: 1.0,
      session_started: 1.4,
      sprint_completed: 1.2,
      session_completed: 1.0,
      participant_left: 0.8,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-vale",
    handle: "vale",
    displayName: "Vale",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/vale/thumb.png",
    archetype: "writer",
    preferredWorldKeys: ["writer-room", "gentle-start", "default"],
    activityBias: {
      participant_joined: 1.0,
      session_started: 1.1,
      sprint_completed: 1.2,
      session_completed: 1.1,
      participant_left: 1.0,
      check_in: 0.8,
      high_five: 0.3,
    },
  },

  // ── Founders (7) ──

  {
    id: "syn-blaze",
    handle: "blaze",
    displayName: "Blaze",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/blaze/thumb.png",
    archetype: "founder",
    preferredWorldKeys: ["yc-build", "vibe-coding", "default"],
    activityBias: {
      participant_joined: 0.9,
      session_started: 1.5,
      sprint_completed: 1.6,
      session_completed: 0.8,
      participant_left: 0.5,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-zara",
    handle: "zara",
    displayName: "Zara",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/zara/thumb.png",
    archetype: "founder",
    preferredWorldKeys: ["yc-build", "default"],
    activityBias: {
      participant_joined: 1.0,
      session_started: 1.3,
      sprint_completed: 1.4,
      session_completed: 1.0,
      participant_left: 0.7,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-ash",
    handle: "ash",
    displayName: "Ash",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/ash/thumb.png",
    archetype: "founder",
    preferredWorldKeys: ["yc-build", "default", "vibe-coding"],
    activityBias: {
      participant_joined: 1.0,
      session_started: 1.2,
      sprint_completed: 1.5,
      session_completed: 1.1,
      participant_left: 0.8,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-cruz",
    handle: "cruz",
    displayName: "Cruz",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/cruz/thumb.png",
    archetype: "founder",
    preferredWorldKeys: ["yc-build", "vibe-coding"],
    activityBias: {
      participant_joined: 0.8,
      session_started: 1.4,
      sprint_completed: 1.5,
      session_completed: 0.9,
      participant_left: 0.6,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-onyx",
    handle: "onyx",
    displayName: "Onyx",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/onyx/thumb.png",
    archetype: "founder",
    preferredWorldKeys: ["yc-build", "default"],
    activityBias: {
      participant_joined: 1.0,
      session_started: 1.1,
      sprint_completed: 1.7,
      session_completed: 1.0,
      participant_left: 0.7,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-tai",
    handle: "tai",
    displayName: "Tai",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/tai/thumb.png",
    archetype: "founder",
    preferredWorldKeys: ["yc-build", "default", "vibe-coding"],
    activityBias: {
      participant_joined: 1.1,
      session_started: 1.3,
      sprint_completed: 1.3,
      session_completed: 1.0,
      participant_left: 0.8,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-rox",
    handle: "rox",
    displayName: "Rox",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/rox/thumb.png",
    archetype: "founder",
    preferredWorldKeys: ["yc-build", "vibe-coding", "default"],
    activityBias: {
      participant_joined: 0.9,
      session_started: 1.4,
      sprint_completed: 1.4,
      session_completed: 0.9,
      participant_left: 0.6,
      check_in: 0.8,
      high_five: 0.3,
    },
  },

  // ── Gentle (7) ──

  {
    id: "syn-haze",
    handle: "haze",
    displayName: "Haze",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/haze/thumb.png",
    archetype: "gentle",
    preferredWorldKeys: ["gentle-start", "default"],
    activityBias: {
      participant_joined: 1.2,
      session_started: 1.0,
      sprint_completed: 1.1,
      session_completed: 1.1,
      participant_left: 1.0,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-dove",
    handle: "dove",
    displayName: "Dove",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/dove/thumb.png",
    archetype: "gentle",
    preferredWorldKeys: ["gentle-start", "writer-room", "default"],
    activityBias: {
      participant_joined: 1.1,
      session_started: 1.1,
      sprint_completed: 1.0,
      session_completed: 1.0,
      participant_left: 0.9,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-elm",
    handle: "elm",
    displayName: "Elm",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/elm/thumb.png",
    archetype: "gentle",
    preferredWorldKeys: ["gentle-start", "default"],
    activityBias: {
      participant_joined: 1.0,
      session_started: 1.0,
      sprint_completed: 1.2,
      session_completed: 1.1,
      participant_left: 0.8,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-rue",
    handle: "rue",
    displayName: "Rue",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/rue/thumb.png",
    archetype: "gentle",
    preferredWorldKeys: ["gentle-start", "writer-room"],
    activityBias: {
      participant_joined: 1.0,
      session_started: 1.1,
      sprint_completed: 1.1,
      session_completed: 1.0,
      participant_left: 1.0,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-cove",
    handle: "cove",
    displayName: "Cove",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/cove/thumb.png",
    archetype: "gentle",
    preferredWorldKeys: ["gentle-start", "default", "writer-room"],
    activityBias: {
      participant_joined: 1.2,
      session_started: 0.9,
      sprint_completed: 1.2,
      session_completed: 1.1,
      participant_left: 0.9,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-jade",
    handle: "jade",
    displayName: "Jade",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/jade/thumb.png",
    archetype: "gentle",
    preferredWorldKeys: ["gentle-start", "default"],
    activityBias: {
      participant_joined: 1.1,
      session_started: 1.0,
      sprint_completed: 1.1,
      session_completed: 1.0,
      participant_left: 1.0,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
  {
    id: "syn-zeph",
    handle: "zeph",
    displayName: "Zeph",
    avatarUrl: "https://lipdyycqbuvibgxcckjd.supabase.co/storage/v1/object/public/avatars/synthetic/zeph/thumb.png",
    archetype: "gentle",
    preferredWorldKeys: ["gentle-start", "writer-room", "default"],
    activityBias: {
      participant_joined: 1.0,
      session_started: 1.1,
      sprint_completed: 1.0,
      session_completed: 1.0,
      participant_left: 0.8,
      check_in: 0.8,
      high_five: 0.3,
    },
  },
];
